/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examcomicpauziah;

/**
 *
 * @author 5470
 */
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
public class formData extends javax.swing.JFrame {

    /**
     * Creates new form formData
     */
    private double grandTotal;
    private DefaultTableModel model;
    private int rowCount;
    
    public formData() {
        initComponents();
        cmbIdBook.setModel(new DefaultComboBoxModel<>(getListBooks()));
        grandTotal = 0.0;
        model = (DefaultTableModel) tblDetailOrder.getModel();
        inputSewa.setEditable(false);

    }
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.koneksiDatabase.BukaKoneksi();
    
    //untuk clear field
    private void Clear(){
        showCustomerName.setText("");
    }
    
    private String[] getListBooks() {
        List<String> kode_buku = new ArrayList<>();
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT id_books FROM buku");
            
            while(rs.next()) {
                String bookId = rs.getString("id_books");
                kode_buku.add(bookId);
            }
                     
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat get data: " + e.getMessage());
        }
        return kode_buku.toArray(String[]::new);
    }
    
    private void getDataBooks() {
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM buku WHERE id_books = '" + cmbIdBook.getSelectedItem().toString() + "'");
            
            LocalDate currentDate = LocalDate.now();
            String today = currentDate.toString();

            while(rs.next()) {
                String nama_buku = rs.getString("nama_buku");
                String harga = rs.getString("harga");

                inputBookName.setText(nama_buku);
                inputHarga.setText(harga);
                inputBookName.setEditable(false);
                inputHarga.setEditable(false);
                inputTglPeminjaman.setText(today);
                inputTglPengembalian.setText(today);
                
            }
                     
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat get data: " + e.getMessage());
        }
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGrandTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        inputSewa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputCustomer = new javax.swing.JTextField();
        inputKaryawan = new javax.swing.JTextField();
        btnViewKaryawanName = new javax.swing.JButton();
        btnViewCustomerName = new javax.swing.JButton();
        showCustomerName = new javax.swing.JTextField();
        showKaryawanName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        inputBookName = new javax.swing.JTextField();
        cmbIdBook = new javax.swing.JComboBox<>();
        inputTglPeminjaman = new javax.swing.JTextField();
        inputTglPengembalian = new javax.swing.JTextField();
        inputHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetailOrder = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputPay = new javax.swing.JTextField();
        showRefund = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("COMIC ZONE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Rental");

        txtGrandTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtGrandTotal.setText("GRAND TOTAL");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        inputSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSewaActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Customer");

        jLabel5.setText("ID Sewa");

        jLabel6.setText("ID Karyawan");

        inputCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCustomerActionPerformed(evt);
            }
        });

        inputKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKaryawanActionPerformed(evt);
            }
        });

        btnViewKaryawanName.setText("View Karyawan name");
        btnViewKaryawanName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewKaryawanNameActionPerformed(evt);
            }
        });

        btnViewCustomerName.setText("View Customer name");
        btnViewCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerNameActionPerformed(evt);
            }
        });

        showCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCustomerNameActionPerformed(evt);
            }
        });

        showKaryawanName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showKaryawanNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnViewCustomerName)
                        .addGap(18, 18, 18)
                        .addComponent(showCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnViewKaryawanName)
                        .addGap(18, 18, 18)
                        .addComponent(showKaryawanName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCustomerName)
                    .addComponent(showCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnViewKaryawanName)
                        .addComponent(showKaryawanName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setText("Kode Buku");

        jLabel11.setText("Nama Buku");

        jLabel12.setText("Tgl peminjaman");

        jLabel13.setText("Tgl pengembalian");

        jLabel14.setText("Harga");

        btnAddItem.setText("tambah item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Hapus item");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        inputBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBookNameActionPerformed(evt);
            }
        });

        cmbIdBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdBookActionPerformed(evt);
            }
        });

        inputTglPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTglPeminjamanActionPerformed(evt);
            }
        });

        inputTglPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTglPengembalianActionPerformed(evt);
            }
        });

        inputHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cmbIdBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(inputBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTglPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTglPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddItem)
                        .addGap(29, 29, 29)
                        .addComponent(btnDeleteItem)))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnDeleteItem)
                    .addComponent(inputBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIdBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTglPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTglPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Detail Order");

        tblDetailOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode buku", "Nama buku", "Tgl peminjaman", "Tgl pengembalian", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tblDetailOrder);

        jLabel8.setText("Bayar");

        jLabel9.setText("Kembalian");

        inputPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputPayMouseExited(evt);
            }
        });
        inputPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPayActionPerformed(evt);
            }
        });
        inputPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputPayKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputPayKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputPayKeyTyped(evt);
            }
        });

        showRefund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRefundActionPerformed(evt);
            }
        });

        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(337, 337, 337))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtGrandTotal)
                        .addGap(161, 161, 161))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(517, 517, 517)
                        .addComponent(jLabel7)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputPay, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showRefund, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrandTotal)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(showRefund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSewaActionPerformed

    private void inputCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCustomerActionPerformed

    private void inputKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKaryawanActionPerformed

    private void btnViewKaryawanNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewKaryawanNameActionPerformed
        // TODO add your handling code here:
        try {
            if(inputKaryawan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID Karyawan tidak boleh ada yang kosong!");
                return;
            }
            st = cn.createStatement();
            rs = st.executeQuery("SELECT nama_karyawan FROM karyawan WHERE id_karyawan = '" + inputKaryawan.getText() + "'");
            
            if(rs.next()) {
                    String nama_karyawan = rs.getString("nama_karyawan");
                    showKaryawanName.setText(nama_karyawan);
                    showKaryawanName.setEditable(false);
                            
                } else {
                    JOptionPane.showMessageDialog(null, "kode karyawan tidak di temukan");
                    Clear();
                   
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat get data: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input nilai tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_btnViewKaryawanNameActionPerformed

    private void btnViewCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerNameActionPerformed
        // TODO add your handling code here:
        try {
            if(inputCustomer.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID customer tidak boleh ada yang kosong!");
                return;
            }
            st = cn.createStatement();
            rs = st.executeQuery("SELECT nama_customer FROM customer WHERE id_customer = '" + inputCustomer.getText() + "'");
            
            if(rs.next()) {
                    String nama_cust = rs.getString("nama_customer");
                    showCustomerName.setText(nama_cust);
                    showCustomerName.setEditable(false);
                            
                } else {
                    JOptionPane.showMessageDialog(null, "kode customer tidak di temukan");
                    Clear();
                   
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan get data: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input nilai tidak valid: " + e.getMessage());
        }
    }//GEN-LAST:event_btnViewCustomerNameActionPerformed

    private void showCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showCustomerNameActionPerformed

    private void showKaryawanNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showKaryawanNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showKaryawanNameActionPerformed

    private void inputPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPayActionPerformed

    private void showRefundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRefundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showRefundActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        String query = "INSERT INTO sewa (id_books, id_customer, id_karyawan, tgl_pinjam, tgl_pengembalian, harga) VALUES (?, ?, ?, ?, ?, ?)";

        try {
            rowCount = model.getRowCount();
            if ( inputCustomer.getText().isEmpty() || inputKaryawan.getText().isEmpty() || rowCount == 0 ||  inputPay.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID Customer, ID Karyawan, Item order, dan jumlah bayar tidak boleh kosong!");
            } else {
                double bayar = Double.parseDouble(inputPay.getText());
                grandTotal = Double.parseDouble(txtGrandTotal.getText());
                double kembalian = bayar - grandTotal;
                if (kembalian < 0) {
                    JOptionPane.showMessageDialog(null, "Kurang bayar!!!!! Rp. " + kembalian);
                    showRefund.setText("");
                } else {
                    showRefund.setText(Double.toString(kembalian));
                    
                    String cek_id_sewa = "SELECT * FROM sewa WHERE id_sewa = '" + inputSewa.getText() + "'";
                    st = cn.createStatement();
                    rs = st.executeQuery(cek_id_sewa);

                    if(rs.next()) {
                        JOptionPane.showMessageDialog(null, "ID Sewa Sudah terdaftar");
                    } else {
                        for (int countRowOrder = 0; countRowOrder < rowCount; countRowOrder++) {
                              
                              Object value_kode_buku = model.getValueAt(countRowOrder, 0);
                              Object value_tanggal_pinjam = model.getValueAt(countRowOrder, 2);
                              Object value_tanggal_kembali = model.getValueAt(countRowOrder, 3);
                              Object value_harga = model.getValueAt(countRowOrder, 4);
                              
                              if (value_kode_buku != null && value_tanggal_pinjam != null && value_tanggal_kembali != null && value_harga != null) {
                                   String kode_buku = value_kode_buku.toString();
                                   String id_customer = inputCustomer.getText();
                                   String id_karyawan = inputKaryawan.getText();
                                   String tanggal_pinjam = value_tanggal_pinjam.toString();
                                   String tanggal_kembali = value_tanggal_kembali.toString();
                                   double harga = Double.parseDouble(value_harga.toString());

                                   PreparedStatement preparedStatement = cn.prepareStatement(query);

                                   preparedStatement.setString(1, kode_buku);
                                   preparedStatement.setString(2, id_customer);
                                   preparedStatement.setString(3, id_karyawan);
                                   preparedStatement.setString(4, tanggal_pinjam);
                                   preparedStatement.setString(5, tanggal_kembali);
                                   preparedStatement.setDouble(6, harga);

                                   preparedStatement.executeUpdate();
                               }                             
                        }

                        JOptionPane.showMessageDialog(null, "Data Berhasil di simpan");
                    }
                }   
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        String kode_buku = cmbIdBook.getSelectedItem().toString();
        String nama_buku = inputBookName.getText();
        String tanggal_pinjam = inputTglPeminjaman.getText();
        String tanggal_kembali = inputTglPengembalian.getText();
        double harga = Double.parseDouble(inputHarga.getText());
        
        rowCount = model.getRowCount();
        
        if(rowCount == 0) {
           model.addRow(new Object[]{kode_buku, nama_buku, tanggal_pinjam, tanggal_kembali, harga});
        } else {
            model.addRow(new Object[]{kode_buku, nama_buku, tanggal_pinjam, tanggal_kembali, harga});
            int lastRowIndex = model.getRowCount() - 1;
            model.moveRow(lastRowIndex, lastRowIndex, 0);
        }
                
        grandTotal += harga;
        txtGrandTotal.setText(String.valueOf(grandTotal));
        
        
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void inputBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBookNameActionPerformed

    private void cmbIdBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdBookActionPerformed
        // TODO add your handling code here:
        getDataBooks(); 
    }//GEN-LAST:event_cmbIdBookActionPerformed

    private void inputTglPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTglPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTglPeminjamanActionPerformed

    private void inputTglPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTglPengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTglPengembalianActionPerformed

    private void inputHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHargaActionPerformed

    private void inputPayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPayKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPayKeyPressed

    private void inputPayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPayKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPayKeyReleased

    private void inputPayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPayKeyTyped

    }//GEN-LAST:event_inputPayKeyTyped

    private void inputPayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPayMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPayMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnViewCustomerName;
    private javax.swing.JButton btnViewKaryawanName;
    private javax.swing.JComboBox<String> cmbIdBook;
    private javax.swing.JTextField inputBookName;
    private javax.swing.JTextField inputCustomer;
    private javax.swing.JTextField inputHarga;
    private javax.swing.JTextField inputKaryawan;
    private javax.swing.JTextField inputPay;
    private javax.swing.JTextField inputSewa;
    private javax.swing.JTextField inputTglPeminjaman;
    private javax.swing.JTextField inputTglPengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField showCustomerName;
    private javax.swing.JTextField showKaryawanName;
    private javax.swing.JTextField showRefund;
    private javax.swing.JTable tblDetailOrder;
    private javax.swing.JLabel txtGrandTotal;
    // End of variables declaration//GEN-END:variables
}
